const M=(question,choices,answer,explanation,source)=>({type:'mcq',question,choices,answer,explanation,source});
const I=(question,answerText,explanation,source,acceptedAnswers=[])=>({type:'identification',question,answerText,acceptedAnswers:[answerText,...acceptedAnswers],explanation,source});
const T=(question,answer,explanation,source)=>({type:'tf',question,choices:['True','False'],answer,explanation,source});
const E=(question,keyPoints,source)=>({type:'essay',question,keyPoints,source});
window.QUIZ_DATA={title:'Food Label',sections:[
{id:'mcq',title:'Multiple Choice',type:'mcq',items:[
M('Which regulation does the lecture identify as governing labels of prepackaged food products in the Philippines?',['A.O. No. 2014-0030','A.O. No. 2000-0010','The 2008 NNS','The PDRI'],0,'The lecture names FDA Administrative Order No. 2014-0030, the Revised Rules and Regulations Governing the Labeling of Prepackaged Food Products.','Slide 4'),
M('Which products are covered by A.O. No. 2014-0030, as described in the slides?',['Locally produced food only','Imported products only','All products, including food supplements, whether imported or locally produced','Only products carrying a nutrition claim'],2,'The slide states that the order covers all products, including food supplements, imported or locally produced.','Slide 4'),
M('How may required food-label information be written under the lecture’s description of the order?',['English only','Filipino only','English, Filipino, or a combination of the two','Any language if the brand name is English'],2,'The slide says label information must be written in English or Filipino, or a combination.','Slide 4'),
M('What is a “product label” in the lecture’s definition?',['A printed advertisement placed near the product','Written, printed, or graphic matter displayed upon the immediate container of an article','The outer shipping carton only','A verbal claim made by a seller'],1,'The lecture defines product label as a means of displaying written, printed, or graphic matter upon the immediate container.','Slide 4'),
M('Which is among the minimum mandatory information listed for a food label?',['A recipe suggestion in every case','Lot identification','A product review score','A country-specific health rating'],1,'Lot identification is one of the listed minimum mandatory items.','Slide 5'),
M('When are directions or instructions for use required by the list in the lecture?',['On every package regardless of need','Where applicable or necessary to ensure correct utilization','Only on imported food','Only when the food has a health claim'],1,'The list says directions/instructions shall also be printed where applicable or necessary to ensure correct utilization.','Slide 5'),
M('Which label claim is not permissible according to the lecture?',['A nutrient content claim that meets FDA guidelines','A health claim allowed by FDA guidance','A therapeutic or medical claim that says a food cures disease','A structure/function description that does not claim to treat disease'],2,'The slides state therapeutic, medical, or curative claims are not permissible; the product would fall under a drug regulatory scheme.','Slide 5'),
M('What is the Principal Display Panel (PDP)?',['The panel containing only nutrition information','The front or facing side of the package most visible to consumers','The back panel listing ingredients','A panel found only on imported foods'],1,'The slide calls the PDP the front part or facing side most visible to consumers.','Slide 7'),
M('Which element is described as where consumers find specific nutrition-related information?',['Principal Display Panel','Ingredient List','Nutrition Facts','Brand name'],2,'The slide identifies the Nutrition Facts element as the place for specific nutrition-related information.','Slide 7'),
M('How does the lecture locate the Information Panel relative to the PDP?',['It is on the right next to and to the right of the PDP','It is always on the bottom of the package','It replaces the PDP on the back','It is inside the ingredient list'],0,'The element slide describes the Information Panel as the information right next to and to the right of the PDP.','Slide 7'),
M('What does the ingredient list show, according to the lecture?',['Only allergens, ordered by severity','All ingredients, including water, spices, and flavors, in order of predominance','Ingredients grouped alphabetically','Only ingredients that contribute calories'],1,'The slide describes the ingredient list as ingredients in the food, including water, spices, and flavors, ordered by predominance.','Slide 10'),
M('Nutrition Facts values are based on what quantity of food?',['The entire package only','One serving, with nutrient information also listed for 100 g or 100 mL','100 g only, regardless of serving size','The amount an individual ate at the last meal'],1,'The serving-size slide says label nutrition information is based on one serving and must also list nutrient information for 100 g or 100 mL.','Slide 11'),
M('A package contains several servings. What does the calorie number on Nutrition Facts represent?',['Calories for the entire package','Calories for one serving','Calories per 100 g only','Calories from fat alone'],1,'The lecture says calories listed are for one serving.','Slide 11'),
M('What does % Daily Value describe on the Nutrition Facts panel?',['The proportion of a serving that is sugar','How nutrients in one serving contribute to the total daily diet','The percentage of the package that is edible','The percentage of nutrients absorbed by the body'],1,'The slide explains that %DV tells how nutrients in one serving contribute to the total daily diet.','Slide 11'),
M('What calorie intake is used as the basis for Daily Values in the lecture?',['1,200 calories','1,500 calories','2,000 calories','2,500 calories'],2,'The Daily Value note on the slide uses a 2,000-calorie diet.','Slide 11'),
M('Which group does the lecture say consumers should try to keep as low as possible each day?',['Dietary fiber, vitamin A, and calcium','Total fat, especially saturated and trans fat, cholesterol, and sodium','Protein, vitamin C, and potassium','Carbohydrate, iron, and water'],1,'The panel guidance says to limit total fat (especially saturated and trans fat), cholesterol, and sodium.','Slide 11'),
M('What distinguishes a “best before” date from the expiration date as described in the slides?',['Best before marks the end of the durable-life period; expiration dates apply to certain foods with strict specifications','Best before is only for supplements; expiration is for all foods','They have identical meanings and apply to every food','Expiration indicates when a package was manufactured'],0,'The lecture says best before marks the end of durable life; expiration dates are required only for certain foods with strict compositional and nutritional specifications.','Slide 15'),
M('Which item does the lecture list among foods requiring an expiration date?',['Fresh apples','Meal replacements','Plain drinking water','All bakery products'],1,'Meal replacements are one of the specified categories: formulated foods that can replace one or more daily meals.','Slide 15'),
M('A claim says “Fiber maintains bowel regularity.” Which category is this in the lecture?',['Nutrient content claim','Health claim','Structure/function claim','Therapeutic claim'],2,'The slide gives this as an example of a structure/function claim describing a role in normal bodily function.','Slide 17'),
M('Under the common nutrient-claim definitions shown, “reduced sugar” means:',['Less than 0.5 g sugar per serving','At least 25% less sugar per serving than the reference food','At least 25% fewer calories than the reference food','No sugar added during processing'],1,'The slide defines reduced sugar as at least 25% less sugar per serving than the reference food.','Slide 18')
]},
{id:'identification',title:'Identification',type:'identification',items:[
I('What FDA administrative order is titled “Revised Rules and Regulations Governing the Labeling of Prepackaged Food Products”?','A.O. No. 2014-0030','This is the order identified by the lecture.','Slide 4',['AO 2014-0030','Administrative Order 2014-0030']),
I('What label element is the package face most visible to consumers called?','Principal Display Panel','The front or facing side most visible to consumers is the PDP.','Slide 7',['PDP']),
I('What panel presents nutrition-related information such as serving size and calories?','Nutrition Facts','The Nutrition Facts panel contains the specific nutrition information described in the lecture.','Slide 7',['Nutrition Facts panel','Nutrition Information']),
I('What list presents ingredients in order of predominance?','Ingredient List','This is the element described on the ingredient-list slide.','Slide 10'),
I('What quantity is the basis for the nutrition information shown on the label?','One serving','The slide says nutrition information is based on one serving.','Slide 11',['Serving size']),
I('What abbreviation names the section showing how one serving contributes nutrients to the daily diet?','% Daily Value','The label uses the percent Daily Value section for this purpose.','Slide 11',['Percent Daily Value','%DV','Daily Value']),
I('What date marks the end of the durable-life period for a prepackaged food?','Best before date','The lecture says best before is also known as a durable life date.','Slide 15',['Best before']),
I('What kind of claim describes a relationship between a food substance and reduced risk of a disease or health-related condition?','Health claim','That is the lecture’s definition of a health claim.','Slide 16'),
I('What claim describes a nutrient’s role in maintaining a structure or normal bodily function?','Structure/function claim','The lecture gives calcium and fiber examples for this category.','Slide 17',['Structure function claim']),
I('What claim category uses terms such as “free,” “high,” “low,” “more,” “reduced,” or “lite”?','Nutrient content claim','These terms describe or compare the level of a nutrient in the product.','Slide 16')
]},
{id:'truefalse',title:'True or False',type:'tf',items:[
T('A.O. No. 2014-0030 covers food supplements that are imported as well as those produced locally.',true,'The lecture explicitly includes both imported and locally produced products, including food supplements.','Slide 4'),
T('A required label statement may be printed in any language as long as it is legible.',false,'The lecture says the information must be in English or Filipino, or a combination. Legibility is a separate requirement.','Slide 4'),
T('The Nutrition Facts panel is the side of the package most visible to consumers.',false,'That describes the Principal Display Panel. Nutrition Facts provides specific nutrition-related information.','Slide 7'),
T('The ingredient list includes ingredients such as water, spices, and flavors, arranged by predominance.',true,'The lecture describes the ingredient list this way.','Slide 10'),
T('A food that is fat-free must also be calorie-free.',false,'The slides caution that fat-free does not necessarily mean calorie-free.','Slide 11'),
T('The lecture says Daily Values are based on a 2,000-calorie diet, though individual energy needs can differ.',true,'Both points appear in the Daily Value guidance.','Slide 11'),
T('An expiration date is required on every prepackaged food product.',false,'The lecture says expiration dates are required only for certain foods with strict compositional and nutritional specifications.','Slide 15'),
T('After an expiration date passes, the food may no longer have the nutrient content declared on its label.',true,'The slide says this may occur, and advises not buying, selling, or eating it after that date.','Slide 15'),
T('A nutrient content claim describes a nutrient level or compares it with another food.',true,'The lecture defines the category in these terms.','Slide 16'),
T('A statement that a food diagnoses or cures a disease is acceptable as a therapeutic claim under the lecture.',false,'Therapeutic, medical, or curative claims are not permissible for food products in the lecture.','Slides 5, 16')
]},
{id:'essay',title:'Essay',type:'essay',items:[
E('Explain why serving size matters when interpreting a Nutrition Facts panel, and describe how to use calories and % Daily Value.',['Nutrition information is based on one serving and also listed per 100 g / 100 mL','Calories refer to one serving; package may contain multiple servings','%DV expresses contribution of one serving to the total daily diet','Daily Values use a 2,000-calorie basis in the lecture; needs can vary'],'Slide 11'),
E('Compare the Principal Display Panel, Information Panel, Ingredient List, and Nutrition Facts by the role each plays.',['PDP: package face most visible to consumers','Information Panel: adjacent/right of PDP according to slide','Ingredient List: all ingredients in order of predominance','Nutrition Facts: serving and nutrient information'],'Slide 7, Slide 10–11'),
E('Distinguish best-before dates from expiration dates and explain the food-handling caution taught in the slides.',['Best before/durable life date indicates end of anticipated quality period for unopened food stored appropriately','Expiration dates apply only to specified categories with strict composition/nutrient specifications','After expiration date, declared nutrient content may not be maintained','Lecture says do not buy, sell, or eat food after expiration; discard it'],'Slide 15'),
E('Compare nutrient content, health, and structure/function claims, including one distinction that prevents a claim from becoming therapeutic.',['Nutrient content claim describes/compares nutrient level','Health claim links food substance to reduced disease risk, subject to criteria described','Structure/function claim describes role in structure or normal bodily function','A claim must not diagnose, cure, mitigate, or treat disease; therapeutic claims are not permitted'],'Slides 5, 16–17'),
E('A shopper sees a low-fat snack with a small serving size and a health-related statement. Explain what label details to check before interpreting the product.',['Serving size and servings per container; values apply per serving','Calories and nutrients; fat-free does not mean calorie-free','%DV and nutrients to limit/get enough','Ingredient list/allergen information, mandatory label information, and whether claims follow FDA guidelines'],'Slides 5, 10–11, 16–18')
]}
]};
