window.QUIZ_DATA = {
  "title": "Web Foundations",
  "topic": "HTML, CSS & JavaScript",
  "questions": [
    {"section":"HTML · STRUCTURE","question":"Which description best explains the role of semantic HTML elements such as <main> and <nav>?","choices":["They describe the purpose of page content to browsers and assistive technology.","They automatically add the site’s colors and spacing.","They replace the need for CSS in responsive layouts.","They make JavaScript execute before the document loads."],"answer":0,"explanation":"Semantic elements communicate the meaning and structure of content. A <main> element identifies primary page content, while <nav> identifies a navigation region. CSS controls visual presentation; JavaScript controls behavior."},
    {"section":"HTML · FORMS","question":"A form control has a visible label beside it. What is the most reliable way to associate the label with the input?","choices":["Put the label text in the input’s placeholder only.","Give the input an id and set the label’s for attribute to the same value.","Put the input inside a <strong> element.","Give the label and input different name attributes."],"answer":1,"explanation":"A label’s for attribute should match the input’s id. This creates a programmatic association, so clicking the label focuses its control and assistive technology can announce the label. Placeholder text is not a substitute for a persistent label."},
    {"section":"CSS · CASCADE","question":"Two CSS rules target the same element with equal specificity. Which rule normally wins?","choices":["The rule with the shorter selector.","The rule written first in the stylesheet.","The rule that appears later in the cascade.","The rule with the property written in uppercase."],"answer":2,"explanation":"When origin, importance, and specificity are otherwise equal, the later declaration in source order wins. This is one part of the CSS cascade; specificity and importance are resolved before source order."},
    {"section":"JAVASCRIPT · VALUES","question":"What does `const items = []` guarantee in JavaScript?","choices":["The array can never contain any values.","The variable cannot be reassigned to a different value, but the array’s contents may change.","The array becomes deeply immutable.","The variable is available only inside the nearest function."],"answer":1,"explanation":"const prevents reassignment of the binding, not mutation of an object or array held by that binding. For example, items.push('x') is allowed, while assigning items = [] again is not. Deep immutability requires a different approach."},
    {"section":"JAVASCRIPT · ASYNC","question":"A function declared with `async` returns what, even when its body returns a plain string?","choices":["A Promise that fulfills with the returned string.","The string directly, unless the function uses await.","A callback that runs on the next page load.","An event listener attached to the document."],"answer":0,"explanation":"An async function always returns a Promise. A returned plain value becomes the fulfillment value of that Promise, so callers can use await or .then() to receive it."}
  ]
}
;
